version: "2"
services:
  mariadb:
    build:
      context: docker/mariadb
    ports:
      - "3306:3306"
    volumes:
      - .:/usr/src/fieryvoid
      - mariadb_data:/var/lib/mysql
    networks:
      - default

  php:
    build:
      context: docker/php
    volumes:
      - .:/usr/src/current
      - composer:/usr/src/fieryvoid/vendor
      - composercache:/root/.composer
      - bashhistory:/root/.bash_history_volume
    networks:
      - default
    develop:
      watch:
        - action: sync
          path: ./source
          target: /usr/src/fieryvoid/source
          ignore:
            - node_modules/

  nginx:
    build:
      context: docker/nginx
    volumes:
      - .:/usr/src/fieryvoid
    ports:
      - "80:80"
    networks:
      - default

networks:
  default:

volumes:
  composer:
    external: false
  composercache:
    external: false
  mariadb_data:
    external: false
  bashhistory:
    external: false
